### ISSUE TITLE
Positional args differ from apenwarr/redo (and thus djb redo too?)

### ISSUE THREAD

**Issue by tv42** [gyepisam/redux#8]
I noticed that $2 doesn't contain the path to the target file. That makes it pretty much useless. And the extension logic might be a bit weird too -- I'm afraid you might not be able to use filepath.Ext.. The other redo implementations seem to behave different.. Reproducing script attached.

$ ./run 
redo  bar/foo.x.y
1=bar/foo.x.y 2=bar/foo
1=bar/foo.x.y 2=foo.x

```
#!/bin/sh
set -e
if [ ! -e apenwarr ]; then
   git clone https://github.com/apenwarr/redo apenwarr
fi

rm -rf tmp
mkdir tmp
cd tmp

echo 'echo "1=$1 2=$2" 1>&2' >default.x.y.do
mkdir bar
PATH="../apenwarr:$PATH" redo bar/foo.x.y
# now with redux
rm -rf .redo
redo-init
redo bar/foo.x.y
```

**Comment by gyepisam** [comment]
redux is now fully compatible on the multiple extension feature and there's no need for a special flag.
It just works and turns out to only affect default scripts with two or more extensions.
